package com.vbrazhnik.vbstorage.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vbrazhnik.vbstorage.entities.Tag;
import com.vbrazhnik.vbstorage.entities.ItemToTag;
import com.vbrazhnik.vbstorage.entities.Item;

import com.vbrazhnik.vbstorage.entities.TagDao;
import com.vbrazhnik.vbstorage.entities.ItemToTagDao;
import com.vbrazhnik.vbstorage.entities.ItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tagDaoConfig;
    private final DaoConfig itemToTagDaoConfig;
    private final DaoConfig itemDaoConfig;

    private final TagDao tagDao;
    private final ItemToTagDao itemToTagDao;
    private final ItemDao itemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        itemToTagDaoConfig = daoConfigMap.get(ItemToTagDao.class).clone();
        itemToTagDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        tagDao = new TagDao(tagDaoConfig, this);
        itemToTagDao = new ItemToTagDao(itemToTagDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);

        registerDao(Tag.class, tagDao);
        registerDao(ItemToTag.class, itemToTagDao);
        registerDao(Item.class, itemDao);
    }
    
    public void clear() {
        tagDaoConfig.clearIdentityScope();
        itemToTagDaoConfig.clearIdentityScope();
        itemDaoConfig.clearIdentityScope();
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public ItemToTagDao getItemToTagDao() {
        return itemToTagDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

}
